spring:
 datasource:
   url: jdbc:h2:file:~/afpa-gestion-culturelle
 jpa:
    hibernate:
      ddl-auto: update

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql