spring:
  datasource:
    url: jdbc:h2:file:~/afpa-gestion-culturelle
  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: always

cda:
  admin:
    nom: user1
    prenom: user1
    password: 1234
  security:
    token:
      secret: cleDeHachagePourSignatureCdA

logging:
  level:
    org:
      springframework:
        web: ERROR
token:
  secret: bF7449XF5lc5iz5sW5Y5suX4d7ok4P7j




#spring:
# datasource:
#  url: jdbc:postgresql://localhost/postgres
#  password: 1234
#  username: user1
# jpa:
#  hibernate:
#   ddl-auto: update

#  properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql

# sgbd H2    
#  datasource:
#    url: jdbc:h2:file:~/afpa-gestion-culturelle