spring:
 datasource:
  url: jdbc:postgresql://localhost/postgres
  password: 1234
  username: user1
 jpa:
  hibernate:
   ddl-auto: update
  properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql

# sgbd H2    
#  datasource:
#    url: jdbc:h2:file:~/afpa-gestion-culturelle