spring:
# sgbd H2    
#  datasource:
#    url: jdbc:h2:file:~/afpa-gestion
 datasource:
  url: jdbc:postgresql://localhost/postgres
  password: 1234
  username: user1

# spring data jpa
 jpa:
  hibernate:
   ddl-auto: update
      


#spring:
# datasource:
#   url: jdbc:h2:file:~/afpa-gestion-culturelle
# CONFIGURATION SPRING DATA JPA
  # CONFIGURATION HIBERNATE 
# jpa:
#    hibernate:
#      ddl-auto: update

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql