spring:
  
# spring-mvc
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      
      # sgbd H2 avec conservation des donnees du fichier   
  datasource:
    url: jdbc:h2:file:~/filrouge
    
    # spring data jpa
  jpa:
    hibernate:
      ddl-auto: update